apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  type: ClusterIP  # Change this to NodePort or LoadBalancer if you need external access
  ports:
    - port: 80  # The port that the service will be accessible on
      targetPort: 8080  # The port that the application is running on in the pod
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}
