pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'jenkins-docker-jgmp'
        KUBECONFIG_CREDENTIALS = 'kubeconfig-secret'
        DOCKER_IMAGE_NAME = "dockeruser111111111/jgmp-test:${env.BUILD_ID}"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    checkout scm
                    def dockerfilePath = 'main/develop/module/module6/Dockerfile'
                    def appImage = docker.build("${DOCKER_IMAGE_NAME}", "-f ${dockerfilePath} .")
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    def appImage = docker.image("${DOCKER_IMAGE_NAME}")
                    docker.withRegistry('https://registry.hub.docker.com', "${DOCKERHUB_CREDENTIALS}") {
                        appImage.push("${env.BUILD_ID}")
                    }
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    kubernetesDeploy(manifests: 'main/develop/module/module6/k8s-manifest.yaml')
                }
            }
        }
    }
}
