version: '3.7'

services:
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=testpass

  module10_rest_app:
    image: test-springboot-rest-app:latest
    ports:
      - 8080:8080
    environment:
      - MYSQL_URL="jdbc:mysql://mysql-container/testdb"
      - MYSQL_USER=testuser
      - MYSQL_PASS=testpass

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/grafana-dashboards:/var/lib/grafana/dashboards
      - ./grafana/grafana-provisioning/dashboards:/etc/grafana/provisioning/dashboards